name: CI/CD

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set Node.js v20
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Build app
              run: npm run build

            - name: Upload to S3
              uses: shallwefootball/s3-upload-action@master
              with:
                  aws_key_id: ${{ secrets.AWS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                  aws_bucket: ${{ secrets.AWS_BUCKET }}
                  source_dir: 'dist'
                  destination_dir: ''
